pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verificar proyecto') {
            steps {
                dir('ASISTEM-D-tests') {
                    bat 'echo Proyecto DermAsystem Serenity BDD verificado'
                    bat 'dir'
                }
            }
        }

        stage('Reporte') {
            steps {
                echo 'Pipeline ejecutado correctamente'
            }
        }
    }

    post {
        always {
            publishHTML(target: [
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'ASISTEM-D-tests/target/site/serenity',
                reportFiles: 'index.html',
                reportName: 'Serenity BDD Report'
            ])
            publishHTML(target: [
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'ASISTEM-D-tests/target/site',
                reportFiles: 'cucumber-report.html',
                reportName: 'Cucumber HTML Report'
            ])
        }
        success {
            echo 'Pipeline exitoso'
        }
    }
}